import Foundation
import Testing
@testable import VPStudio

@Suite("PlayerExternalSubtitleWriter")
struct PlayerExternalSubtitleWriterTests {
    @Test
    func prefersSupportedSourceFormat() throws {
        let subtitle = Subtitle(
            id: "1",
            language: "en",
            fileName: "movie.txt",
            url: "https://example.com/subtitle",
            format: .vtt
        )

        #expect(try PlayerExternalSubtitleWriter.resolvedFormat(for: subtitle) == .vtt)
    }

    @Test
    func fallsBackToFilenameExtensionWhenFormatIsUnknown() throws {
        let subtitle = Subtitle(
            id: "1",
            language: "en",
            fileName: "movie.ass",
            url: "https://example.com/subtitle",
            format: .unknown
        )

        #expect(try PlayerExternalSubtitleWriter.resolvedFormat(for: subtitle) == .ass)
    }

    @Test
    func fileURLAppendsDeterministicIDAndResolvedExtension() {
        let rootDirectory = URL(fileURLWithPath: "/tmp/vpstudio-subtitles", isDirectory: true)

        let fileURL = PlayerExternalSubtitleWriter.fileURL(
            in: rootDirectory,
            fileID: "subtitle-track",
            format: .vtt
        )

        #expect(fileURL == rootDirectory.appendingPathComponent("subtitle-track.vtt"))
    }

    @Test
    func throwsWhenFormatCannotBeResolved() {
        let subtitle = Subtitle(
            id: "1",
            language: "en",
            fileName: "movie.txt",
            url: "https://example.com/subtitle",
            format: .unknown
        )

        #expect(throws: CocoaError.self) {
            try PlayerExternalSubtitleWriter.resolvedFormat(for: subtitle)
        }
    }

    @Test
    func writeRejectsUnsupportedSourceBeforeEvaluatingFileID() {
        let subtitle = Subtitle(
            id: "1",
            language: "en",
            fileName: "movie.txt",
            url: "https://example.com/subtitle",
            format: .unknown
        )
        var evaluatedFileID = false

        #expect(throws: CocoaError.self) {
            try PlayerExternalSubtitleWriter.write(
                content: "1\nHello\n",
                source: subtitle,
                fileID: {
                    evaluatedFileID = true
                    return "should-not-be-used"
                }()
            )
        }
        #expect(evaluatedFileID == false)
    }

    @Test
    func writesContentToDeterministicTemporaryLocation() throws {
        let rootDirectory = FileManager.default.temporaryDirectory
            .appendingPathComponent(UUID().uuidString, isDirectory: true)
        try FileManager.default.createDirectory(
            at: rootDirectory,
            withIntermediateDirectories: true,
            attributes: nil
        )
        defer { try? FileManager.default.removeItem(at: rootDirectory) }

        let subtitle = Subtitle(
            id: "1",
            language: "en",
            fileName: "movie.srt",
            url: "https://example.com/subtitle",
            format: .unknown
        )

        let fileURL = try PlayerExternalSubtitleWriter.write(
            content: "1\nHello\n",
            source: subtitle,
            directory: rootDirectory,
            fileID: "fixture-subtitle"
        )

        #expect(fileURL == rootDirectory.appendingPathComponent("fixture-subtitle.srt"))
        #expect(try String(contentsOf: fileURL, encoding: .utf8) == "1\nHello\n")
    }

    @Test
    func writeUsesDefaultDirectoryAndAutoGeneratedFileID() throws {
        let subtitle = Subtitle(
            id: "1",
            language: "en",
            fileName: "movie.ass",
            url: "https://example.com/subtitle",
            format: .unknown
        )

        let fileURL = try PlayerExternalSubtitleWriter.write(
            content: "[Script Info]\n",
            source: subtitle
        )
        defer { try? FileManager.default.removeItem(at: fileURL) }

        #expect(fileURL.deletingLastPathComponent().standardizedFileURL.path == FileManager.default.temporaryDirectory.standardizedFileURL.path)
        #expect(fileURL.pathExtension == "ass")
        #expect(try String(contentsOf: fileURL, encoding: .utf8) == "[Script Info]\n")
    }
}
