import Foundation

extension Notification.Name {
    static let libraryDidChange = Notification.Name("VPStudio.LibraryDidChange")
    static let tasteProfileDidChange = Notification.Name("VPStudio.TasteProfileDidChange")
    static let settingsDidChange = Notification.Name("VPStudio.SettingsDidChange")
    static let discoverAISettingsDidChange = Notification.Name("VPStudio.DiscoverAISettingsDidChange")
    static let downloadsDidChange = Notification.Name("VPStudio.DownloadsDidChange")
    static let watchHistoryDidChange = Notification.Name("VPStudio.WatchHistoryDidChange")
    static let openSubtitlesDidChange = Notification.Name("VPStudio.OpenSubtitlesDidChange")
    static let environmentsDidChange = Notification.Name("VPStudio.EnvironmentsDidChange")
    static let indexersDidChange = Notification.Name("VPStudio.IndexersDidChange")
    static let tmdbApiKeyDidChange = Notification.Name("VPStudio.TMDBApiKeyDidChange")
    static let appDidResetAllData = Notification.Name("VPStudio.AppDidResetAllData")
    static let localModelsDidChange = Notification.Name("VPStudio.LocalModelsDidChange")

    // Immersive space control bridge
    static let immersiveTapCatcherDidFire = Notification.Name("VPStudio.ImmersiveTapCatcherDidFire")
    static let immersiveControlTogglePlayPause = Notification.Name("VPStudio.ImmersiveControl.TogglePlayPause")
    static let immersiveControlSeekBack = Notification.Name("VPStudio.ImmersiveControl.SeekBack")
    static let immersiveControlSeekForward = Notification.Name("VPStudio.ImmersiveControl.SeekForward")
    static let immersiveControlSeekToPercent = Notification.Name("VPStudio.ImmersiveControl.SeekToPercent")
    static let immersiveControlPreviousChapter = Notification.Name("VPStudio.ImmersiveControl.PreviousChapter")
    static let immersiveControlNextChapter = Notification.Name("VPStudio.ImmersiveControl.NextChapter")
    static let immersiveControlCycleRate = Notification.Name("VPStudio.ImmersiveControl.CycleRate")
    static let immersiveControlToggleSubtitles = Notification.Name("VPStudio.ImmersiveControl.ToggleSubtitles")
    static let immersiveControlToggleAudio = Notification.Name("VPStudio.ImmersiveControl.ToggleAudio")
    static let immersiveControlRequestEnvironmentSwitch = Notification.Name("VPStudio.ImmersiveControl.RequestEnvironmentSwitch")
    static let immersiveControlDismiss = Notification.Name("VPStudio.ImmersiveControl.Dismiss")
    static let immersiveControlCycleScreenSize = Notification.Name("VPStudio.ImmersiveControl.CycleScreenSize")
    static let playerAutoplayControlPlayNow = Notification.Name("VPStudio.PlayerAutoplayControl.PlayNow")
    static let playerAutoplayControlCancel = Notification.Name("VPStudio.PlayerAutoplayControl.Cancel")
    static let playerAutoplayControlProgress = Notification.Name("VPStudio.PlayerAutoplayControl.Progress")
    static let playerSubtitleControlRefreshCatalog = Notification.Name("VPStudio.PlayerSubtitleControl.RefreshCatalog")
    static let playerSubtitleControlDownload = Notification.Name("VPStudio.PlayerSubtitleControl.Download")
    static let libraryCSVImportControlImportFiles = Notification.Name("VPStudio.LibraryCSVImportControl.ImportFiles")
    static let libraryCSVImportControlImportFolder = Notification.Name("VPStudio.LibraryCSVImportControl.ImportFolder")
    static let aiSettingsControlPersistCloudCredential = Notification.Name("VPStudio.AISettingsControl.PersistCloudCredential")
    static let aiSettingsControlDeleteCloudCredential = Notification.Name("VPStudio.AISettingsControl.DeleteCloudCredential")
    static let aiSettingsControlPersistOllamaEndpoint = Notification.Name("VPStudio.AISettingsControl.PersistOllamaEndpoint")
    static let aiSettingsControlPersistStringSetting = Notification.Name("VPStudio.AISettingsControl.PersistStringSetting")
    static let aiSettingsControlPersistBoolSetting = Notification.Name("VPStudio.AISettingsControl.PersistBoolSetting")
    static let aiSettingsControlScheduleModelPresetSave = Notification.Name("VPStudio.AISettingsControl.ScheduleModelPresetSave")
    static let aiSettingsControlResetUsageStats = Notification.Name("VPStudio.AISettingsControl.ResetUsageStats")
}
